include:
  - 'https://gitlab-templates.ddbuild.io/slack-notifier/v1/template.yml'

variables:
  # TODO: Detect unity location in script.
  UNITY_HOME: "/Applications/Unity/Unity.app/Contents/"
  UNITY_PATH: "$UNITY_HOME/MacOS/Unity"
  UNITY_SUPPORT_PATH: "/Library/Application Support/Unity/config"


stages:
  - unit-test

.shared:
  install-dependencies:
    - pip install saxonche
  create-server-config:
    - vault login -method=aws -no-print
    - export UNITY_SERVER_CONFIG=$(vault kv get -field=config kv/aws/arn:aws:iam::486234852809:role/ci-dd-sdk-unity/server-config)
    - mkdir -p "$UNITY_SUPPORT_PATH"
    - printf "%s\n" "$UNITY_SERVER_CONFIG" > "$UNITY_SUPPORT_PATH/services-config.json"

unit-test:
  stage: unit-test
  tags:
    - macos:sonoma
    - specific:true
  script:
    - !reference [.shared, install-dependencies]
    - !reference [.shared, create-server-config]
    - cd tools/scripts && python ./run_unit_test.py
  artifacts:
    when: always
    expire_in: "30 days"
    reports:
      junit: $CI_PROJECT_DIR/samples/Datadog Sample/tmp/junit-results.xml
