include:
  - 'https://gitlab-templates.ddbuild.io/slack-notifier/v1/template.yml'

variables:
  DOCKER_CI_IMAGE: registry.ddbuild.io/docker:24.0.4-gbi-focal

stages:
  - test

unit-test-docker:
  stage: test
  image: $DOCKER_CI_IMAGE
  tags: [ "arch:amd64" ]
  script:
    - apt-get install -y netcat
    - echo "GET / HTTP/1.1" | nc -v unity-licensing-server.rum.all-clusters.local-dc.fabric.dog 8080

unit-test-mac:
  stage: test
  tags:
    - macos:sonoma
    - specific:true
  script:
    - echo "GET / HTTP/1.1" | nc -v unity-licensing-server.rum.all-clusters.local-dc.fabric.dog 8080
