include:
  - 'https://gitlab-templates.ddbuild.io/slack-notifier/v1/template.yml'

variables:
  # TODO: Detect unity location in script.
  UNITY_VERSION: "2022.3.54f1"
  UNITY_SUPPORT_PATH: "/Library/Application Support/Unity/config"
  IS_ON_CI: "1"

stages:
  - unit-test
  - integration-test

.shared:
  install-dependencies:
    - echo 'Installing Unity Hub...'
    - brew install --cask unity-hub
    - echo 'Installing Unity Editor and Modules...'
    # This can fail if Unity is already installed, so || true
    - /Applications/Unity\ Hub.app/Contents/MacOS/Unity\ Hub -- --headless install --version "$UNITY_VERSION" --module ios android --architecture arm64 --childModules || true
  create-server-config:
    - vault login -method=aws -no-print
    - export UNITY_SERVER_CONFIG=$(vault kv get -field=config kv/aws/arn:aws:iam::486234852809:role/ci-dd-sdk-unity/server-config)
    - sudo mkdir -p "$UNITY_SUPPORT_PATH"
    - printf "%s\n" "$UNITY_SERVER_CONFIG" > sudo tee "$UNITY_SUPPORT_PATH/services-config.json"
    - sudo chmod -R +r "$UNITY_SUPPORT_PATH"

unit-test:
  stage: unit-test
  tags:
    - macos:sonoma
    - specific:true
  script:
    - !reference [.shared, install-dependencies]
    - !reference [.shared, create-server-config]
    - cd $CI_PROJECT_DIR/tools/scripts
    - python3 -m venv venv && ./venv/bin/pip3 install -r requirements.txt
    - ./venv/bin/python3 ./run_unit_test.py
  artifacts:
    when: always
    expire_in: "30 days"
    reports:
      junit: $CI_PROJECT_DIR/samples/Datadog Sample/tmp/junit-results*.xml

integration-test:
  stage: integration-test
  tags:
    - macos:sonoma
    - specific:true
  script:
    - !reference [.shared, install-dependencies]
    - !reference [.shared, create-server-config]
    - cd $CI_PROJECT_DIR/tools/mock_server
    - python3 -m venv venv && ./venv/bin/pip3 install -r requirements.txt
    - ./venv/bin/python3 app.py --update-schemas
    - cd $CI_PROJECT_DIR/tools/scripts
    - python3 -m venv venv && ./venv/bin/pip3 install -r requirements.txt
    - ./venv/bin/python3 ./run_integration_test.py --platform ios --launch-simulator
    - ./venv/bin/python3 ./run_integration_test.py --platform android --launch-simulator
  artifacts:
    when: always
    expire_in: "30 days"
    reports:
      junit: $CI_PROJECT_DIR/samples/Datadog Sample/tmp/*_results.xml
