include:
  - 'https://gitlab-templates.ddbuild.io/slack-notifier/v1/template.yml'

variables:
  UNITY_SUPPORT_PATH: "/Library/Application Support/Unity/config"

stages:
  - unit-test

.shared:
  create-server-config:
    - vault login -method=aws -no-print
    - export UNITY_SERVER_CONFIG=$(vault kv get -field=config kv/aws/arn:aws:iam::486234852809:role/ci-dd-sdk-unity/server-config)
    - mkdir -p "$UNITY_SUPPORT_PATH"
    - printf "%s\n" "$UNITY_SERVER_CONFIG" > "$UNITY_SUPPORT_PATH/server-config.json"

unit-test:
  stage: unit-test
  tags:
    - macos:sonoma
    - specific:true
  script:
    - !reference [.shared, create-server-config]
    - cd tools/scripts && ./run_unit_test.py
