include:
  - 'https://gitlab-templates.ddbuild.io/slack-notifier/v1/template.yml'
stages:
  - test
unit-test-mac:
  stage: test
  tags:
    - macos:sonoma
    - specific:true
  script:
    - echo "GET / HTTP/1.1" | nc -v unity-licensing-server.us1.ddbuild.io 80
